version: '3.8'

services:
  bot:
    build: .
    container_name: isp_telegram_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - REPORTS_CHANNEL_ID=${REPORTS_CHANNEL_ID}
    volumes:
      - ./isp_bot.db:/app/isp_bot.db
      - ./bot.log:/app/bot.log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
